### ISSUE TITLE
Starting new transcription chunk

### ISSUE THREAD

**Issue by mtrgmbn** [warmans/rsk-search#19]
On the 'Contribute' page on Scrimpton, I press 'Start Now'
I get taken to a chunk that I've already made a submission on that's awaiting approval, so I click the prompt at the top of the page that says "There are already 1 approved or proposed contributions for this section of audio. You can start a different one by clicking here."
But when I click the hyperlink on the last word 'here', the page refreshes and I get taken to the same chunk that I started on.

I'm sure there might be more to work on as the website says there are 22 episodes that require transcription

**Comment by warmans** [comment]
Why did you close this? What was the resolution?

I've observed in the past that when it gets up to a high completion % that sometimes the suggestions can't find an eligible chunk. I thought I'd fixed this last time around but perhaps there is still an issue.

**Comment by mtrgmbn** [comment]
I'd closed the issue as it seemed to have resolved itself, somehow! It
stopped being stuck on the one chunk it kept taking me to, maybe it just
needed some time.
