### ISSUE TITLE
Some audio clips are incorrect

### ISSUE THREAD

**Issue by majolo** [warmans/rsk-search#21]
I've found that sometimes that audio doesn't match the transcript, for example the audio on https://scrimpton.com/ep/ep-xfm-S1E17 appears to match the transcript for S1E18 instead. I believe this may be the case for other episodes also.

**Comment by warmans** [comment]
That's weird. You don't happen to know which is correct do you (e.g. if the transcript or the audio is mislabeled)?

**Comment by warmans** [comment]
I've fixed S1E16, S1E17 and S1E18. I'm going to go though all the rest and see if I can find any other discrepancies. Thanks for the report.
