### ISSUE TITLE
Audio on S2E49 is unedited

### ISSUE THREAD

**Issue by majolo** [warmans/rsk-search#22]
The audio on S2E49 hasn't had the music trimmed and adverts removed, the transcript is correct but this means the timestamps don't match.

https://scrimpton.com/ep/ep-xfm-S2E49

**Comment by majolo** [comment]
Nice, big fan of the site by the way (if you couldn't tell 😄)!

**Comment by warmans** [comment]
Edited file uploaded and audio offsets reset. Will need to put some manual timestamps back in at some point.
