### ISSUE TITLE
Autosave/Save not working

### ISSUE THREAD

**Issue by Notnif** [warmans/rsk-search#4]
Before, when editing a part of an episode it used to save constantly (bottom right would always say "Saved less than a minute ago.")

Now, after the new episodes were added for transcribing, it only seems to save when creating a draft. Even pressing save manually doesn't work for me (after clicking Save it still says "Saved X minutes/hour ago.")

A workaround I use is to copy and paste the transcript into Text/Word doc and then paste it back into the draft before submitting it.

Even when switching from Editor to Preview view and back, you can lose your transcription progress.

**Comment by warmans** [comment]
Ah, crap thanks for opening this. I hadn't even remotely integrated that properly after re-factoring the editor. I've deployed a fix but it may require a hard refresh to ensure you have the latest version (crtl+f5). Please re-open the issue if it's still doing something weird.
